AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue project CloudFormation template'

########################################
############### Metadata ################
########################################
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'General TAGs'
        Parameters:
          - ProjectCode
          - ProjectName
          - Environment
      - Label:
          default: 'General Settings'
        Parameters:
          - WorkflowName
          - TriggerName
          - JobName
          - S3BucketTemp
          - S3BucketCode
          - ScriptLocation
          - RoleName

########################################
############## Parameters ##############
########################################
Parameters:
  ProjectCode:
    Type: String
    Description: 'Project code'
    AllowedPattern: '^[A-Z0-9]*$'
    Default: PRJ001
  ProjectName:
    Type: String
    Description: 'Project name'
    AllowedPattern: '^[a-zA-Z0-9-]*$'
    Default: Glue-Project
  Environment:
    Type: String
    Description: 'Environment'
    AllowedValues:
      - DEV
      - STG
      - PROD
    Default: DEV

  WorkflowName:
    Type: String
    Description: 'Glue workflow name'
    Default: EtlData-Workflow
  TriggerName:
    Type: String
    Description: 'Trigger name for Glue job'
    Default: EtlData-Trigger
  JobName:
    Type: String
    Description: 'Glue job name'
    Default: GlueJob-ETL-Data-Workflow
  S3BucketTemp:
    Type: String
    Description: 'Temporary S3 bucket for Glue job'
    Default: my-temp-bucket
  S3BucketCode:
    Type: String
    Description: 'S3 bucket for Glue job scripts'
    Default: data-engineer-juanmgart
  ScriptLocation:
    Type: String
    Description: 'S3 location of the Glue job script'
    Default: scripts/DataWkflow-Job.py
  RoleName:
    Type: String
    Description: 'IAM role for Glue job'
    Default: GlueJobRole

########################################
############## Resources ###############
########################################
Resources:
  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Name: !Sub '${ProjectCode}-${ProjectName}-${WorkflowName}-${Environment}-${AWS::StackName}'
      Description: 'Workflow for Glue project'
      DefaultRunProperties: {}
      Tags:
        ProjectCode: !Ref ProjectCode
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectCode}-${ProjectName}-${RoleName}-${Environment}-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectCode}-${ProjectName}-Policy-${Environment}-${AWS::StackName}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:*
                  - s3:*
                  - logs:*
                Resource: '*'
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: trusted_data_data_engineer
        Description: 'Database for trusted data'
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${ProjectCode}-${ProjectName}-${JobName}-${Environment}-${AWS::StackName}'
      Role: !Ref GlueJobRole
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${S3BucketCode}/${ScriptLocation}'
      DefaultArguments:
        --TempDir: !Sub 's3://${S3BucketTemp}/'
        --job-language: python
      Tags:
        ProjectCode: !Ref ProjectCode
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  GlueJobTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub '${ProjectCode}-${ProjectName}-${TriggerName}-${Environment}-${AWS::StackName}'
      Type: SCHEDULED
      Schedule: cron(0 12 * * ? *)
      Actions:
        - JobName: !Ref GlueJob
      WorkflowName: !Ref GlueWorkflow
      Tags:
        ProjectCode: !Ref ProjectCode
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain